python convert-pretrained-swin-model-to-d2.py swin_tiny_patch4_window7_224.pth                    swin_tiny_patch4_window7_224.pkl                      
python convert-pretrained-swin-model-to-d2.py swin_tiny_patch4_window7_224_22k.pth                swin_tiny_patch4_window7_224_22k.pkl                      
python convert-pretrained-swin-model-to-d2.py swin_tiny_patch4_window7_224_22kto1k_finetune.pth   swin_tiny_patch4_window7_224_22kto1k_finetune.pkl                      
python convert-pretrained-swin-model-to-d2.py swin_small_patch4_window7_224.pth                   swin_small_patch4_window7_224.pkl                      
python convert-pretrained-swin-model-to-d2.py swin_small_patch4_window7_224_22k.pth               swin_small_patch4_window7_224_22k.pkl                      
python convert-pretrained-swin-model-to-d2.py swin_small_patch4_window7_224_22kto1k_finetune.pth  swin_small_patch4_window7_224_22kto1k_finetune.pkl                      
python convert-pretrained-swin-model-to-d2.py swin_base_patch4_window7_224.pth                    swin_base_patch4_window7_224.pkl                                 
python convert-pretrained-swin-model-to-d2.py swin_base_patch4_window7_224_22k.pth                swin_base_patch4_window7_224_22k.pkl                             
python convert-pretrained-swin-model-to-d2.py swin_base_patch4_window7_224_22kto1k.pth            swin_base_patch4_window7_224_22kto1k.pkl                         
python convert-pretrained-swin-model-to-d2.py swin_base_patch4_window12_384.pth                   swin_base_patch4_window12_384.pkl                                
python convert-pretrained-swin-model-to-d2.py swin_base_patch4_window12_384_22k.pth               swin_base_patch4_window12_384_22k.pkl                            
python convert-pretrained-swin-model-to-d2.py swin_base_patch4_window12_384_22kto1k.pth           swin_base_patch4_window12_384_22kto1k.pkl                        
python convert-pretrained-swin-model-to-d2.py swin_large_patch4_window7_224_22k.pth               swin_large_patch4_window7_224_22k.pkl                      
python convert-pretrained-swin-model-to-d2.py swin_large_patch4_window7_224_22kto1k.pth           swin_large_patch4_window7_224_22kto1k.pkl                      
python convert-pretrained-swin-model-to-d2.py swin_large_patch4_window12_384_22k.pth              swin_large_patch4_window12_384_22k.pkl                           
python convert-pretrained-swin-model-to-d2.py swin_large_patch4_window12_384_22kto1k.pth          swin_large_patch4_window12_384_22kto1k.pkl                      
